### ISSUE TITLE
installing version 1.0.0 creates error on startup

### ISSUE THREAD

**Issue by Ian-Nicholls89** [Ian-Nicholls89/exPYre#1]
Traceback (most recent call last):
  File "exPYre.py", line 692, in <module>
  File "exPYre.py", line 656, in main
  File "exPYre.py", line 627, in start_timer
  File "exPYre.py", line 601, in trigger_database_scan
  File "exPYre.py", line 437, in show_toast
  File "windows_toasts\toasters.py", line 243, in show_toast
  File "windows_toasts\toasters.py", line 135, in show_toast
  File "windows_toasts\toasters.py", line 40, in _build_adaptable_data
ModuleNotFoundError: No module named 'winrt.windows.foundation.collections'

**Comment by Ian-Nicholls89** [comment]
fixed by completely deleting previous compiled files and including --hidden-import winrt.windows.foundation.collections in new pyinstaller compile
